### ISSUE TITLE
epg neatnaujintas

### ISSUE THREAD

**Issue by SerasAntanas** [Povilas1/Skynet-IPTV-With-EPG#22]
guide.xml nebeatsinaujino .

**Comment by Povilas1** [comment]
Šis repo negarantuoja, kad EPG visad bus atnaujintas, todėl ir yra guide, kaip generuotis pačiam.

**Comment by kazikazka** [comment]
Gal galima nuorodą į tą guide? Niekur nerandu. Tools direktorijoj mačiau yra scriptai, bet ne pilnai suprantu jų turinį.
