### ISSUE TITLE
GMT

### ISSUE THREAD

**Issue by karkaaa** [Povilas1/Skynet-IPTV-With-EPG#4]
Sveiki,

Kaip pasukti 3val. GMT?

**Comment by Povilas1** [comment]
Sveikas, 

šito turi klausti savo IPTV appso puslapyje :)

**Comment by megamorphf** [comment]
@karkaaa paskaityk [čia][https://github.com/Povilas1/Skynet-IPTV-With-EPG#epg-laiko-pasukimas]
