### ISSUE TITLE
TV3 ir TV6 HD

### ISSUE THREAD

**Issue by tomasvilda** [Povilas1/Skynet-IPTV-With-EPG#6]
Neturiu galimybės praskanuoti, gal kas jau rado IP?

**Comment by Dzekeris** [comment]
Aš patiems Skynet rašiau, jie dar netransliuoja HD raišką šių kanalų.

**Comment by tomasvilda** [comment]
https://forum.evpro.lt/it-naujienos/tv3-tv6/ paskutinėje žinutėje sako kitaip

**Comment by Dzekeris** [comment]
@tomasvilda gali būt kad rodo jau, rašiau aš jiems sausio 2d :D

**Comment by zyga196** [comment]
prašom

#EXTINF:-1,TV3 HD
udp://@239.255.12.13:1234
#EXTINF:-1,TV6 HD
udp://@239.255.12.16:1234

**Comment by Povilas1** [comment]
Pridėjau, uždarau temą. 👍
